#define crypt_argchk fun_crypt_argchk

// cfg
//#define XMALLOC fun_XMALLOC
//#define XREALLOC fun_XREALLOC
//#define XCALLOC fun_XCALLOC
//#define XFREE fun_XFREE
//#define XQSORT fun_XQSORT
//#define XCLOCK fun_XCLOCK
//#define XMEMCPY fun_XMEMCPY
//#define XMEMCMP fun_XMEMCMP
//#define XMEMSET fun_XMEMSET
//#define XSTRCMP fun_XSTRCMP

//ciper
#define blowfish_setup fun_blowfish_setup
#define blowfish_ecb_encrypt fun_blowfish_ecb_encrypt
#define blowfish_ecb_decrypt fun_blowfish_ecb_decrypt
#define blowfish_test fun_blowfish_test
#define blowfish_done fun_blowfish_done
#define blowfish_keysize fun_blowfish_keysize
#define rc5_setup fun_rc5_setup
#define rc5_ecb_encrypt fun_rc5_ecb_encrypt
#define rc5_ecb_decrypt fun_rc5_ecb_decrypt
#define rc5_test fun_rc5_test
#define rc5_done fun_rc5_done
#define rc5_keysize fun_rc5_keysize
#define rc6_setup fun_rc6_setup
#define rc6_ecb_encrypt fun_rc6_ecb_encrypt
#define rc6_ecb_decrypt fun_rc6_ecb_decrypt
#define rc6_test fun_rc6_test
#define rc6_done fun_rc6_done
#define rc6_keysize fun_rc6_keysize
#define rc2_setup fun_rc2_setup
#define rc2_ecb_encrypt fun_rc2_ecb_encrypt
#define rc2_ecb_decrypt fun_rc2_ecb_decrypt
#define rc2_test fun_rc2_test
#define rc2_done fun_rc2_done
#define rc2_keysize fun_rc2_keysize
#define saferp_setup fun_saferp_setup
#define saferp_ecb_encrypt fun_saferp_ecb_encrypt
#define saferp_ecb_decrypt fun_saferp_ecb_decrypt
#define saferp_test fun_saferp_test
#define saferp_done fun_saferp_done
#define saferp_keysize fun_saferp_keysize
#define safer_k64_setup fun_safer_k64_setup
#define safer_sk64_setup fun_safer_sk64_setup
#define safer_k128_setup fun_safer_k128_setup
#define safer_sk128_setup fun_safer_sk128_setup
#define safer_ecb_encrypt fun_safer_ecb_encrypt
#define safer_ecb_decrypt fun_safer_ecb_decrypt
#define safer_k64_test fun_safer_k64_test
#define safer_sk64_test fun_safer_sk64_test
#define safer_sk128_test fun_safer_sk128_test
#define safer_done fun_safer_done
#define safer_64_keysize fun_safer_64_keysize
#define safer_128_keysize fun_safer_128_keysize
#define rijndael_setup fun_rijndael_setup
#define rijndael_ecb_encrypt fun_rijndael_ecb_encrypt
#define rijndael_ecb_decrypt fun_rijndael_ecb_decrypt
#define rijndael_test fun_rijndael_test
#define rijndael_done fun_rijndael_done
#define rijndael_keysize fun_rijndael_keysize
#define rijndael_enc_setup fun_rijndael_enc_setup
#define rijndael_enc_ecb_encrypt fun_rijndael_enc_ecb_encrypt
#define rijndael_enc_done fun_rijndael_enc_done
#define rijndael_enc_keysize fun_rijndael_enc_keysize
#define xtea_setup fun_xtea_setup
#define xtea_ecb_encrypt fun_xtea_ecb_encrypt
#define xtea_ecb_decrypt fun_xtea_ecb_decrypt
#define xtea_test fun_xtea_test
#define xtea_done fun_xtea_done
#define xtea_keysize fun_xtea_keysize
#define twofish_setup fun_twofish_setup
#define twofish_ecb_encrypt fun_twofish_ecb_encrypt
#define twofish_ecb_decrypt fun_twofish_ecb_decrypt
#define twofish_test fun_twofish_test
#define twofish_done fun_twofish_done
#define twofish_keysize fun_twofish_keysize
#define des_setup fun_des_setup
#define des_ecb_encrypt fun_des_ecb_encrypt
#define des_ecb_decrypt fun_des_ecb_decrypt
#define des_test fun_des_test
#define des_done fun_des_done
#define des_keysize fun_des_keysize
#define des3_setup fun_des3_setup
#define des3_ecb_encrypt fun_des3_ecb_encrypt
#define des3_ecb_decrypt fun_des3_ecb_decrypt
#define des3_test fun_des3_test
#define des3_done fun_des3_done
#define des3_keysize fun_des3_keysize
#define cast5_setup fun_cast5_setup
#define cast5_ecb_encrypt fun_cast5_ecb_encrypt
#define cast5_ecb_decrypt fun_cast5_ecb_decrypt
#define cast5_test fun_cast5_test
#define cast5_done fun_cast5_done
#define cast5_keysize fun_cast5_keysize
#define noekeon_setup fun_noekeon_setup
#define noekeon_ecb_encrypt fun_noekeon_ecb_encrypt
#define noekeon_ecb_decrypt fun_noekeon_ecb_decrypt
#define noekeon_test fun_noekeon_test
#define noekeon_done fun_noekeon_done
#define noekeon_keysize fun_noekeon_keysize
#define skipjack_setup fun_skipjack_setup
#define skipjack_ecb_encrypt fun_skipjack_ecb_encrypt
#define skipjack_ecb_decrypt fun_skipjack_ecb_decrypt
#define skipjack_test fun_skipjack_test
#define skipjack_done fun_skipjack_done
#define skipjack_keysize fun_skipjack_keysize
#define khazad_setup fun_khazad_setup
#define khazad_ecb_encrypt fun_khazad_ecb_encrypt
#define khazad_ecb_decrypt fun_khazad_ecb_decrypt
#define khazad_test fun_khazad_test
#define khazad_done fun_khazad_done
#define khazad_keysize fun_khazad_keysize
#define anubis_setup fun_anubis_setup
#define anubis_ecb_encrypt fun_anubis_ecb_encrypt
#define anubis_ecb_decrypt fun_anubis_ecb_decrypt
#define anubis_test fun_anubis_test
#define anubis_done fun_anubis_done
#define anubis_keysize fun_anubis_keysize
#define kseed_setup fun_kseed_setup
#define kseed_ecb_encrypt fun_kseed_ecb_encrypt
#define kseed_ecb_decrypt fun_kseed_ecb_decrypt
#define kseed_test fun_kseed_test
#define kseed_done fun_kseed_done
#define kseed_keysize fun_kseed_keysize
#define kasumi_setup fun_kasumi_setup
#define kasumi_ecb_encrypt fun_kasumi_ecb_encrypt
#define kasumi_ecb_decrypt fun_kasumi_ecb_decrypt
#define kasumi_test fun_kasumi_test
#define kasumi_done fun_kasumi_done
#define kasumi_keysize fun_kasumi_keysize
#define multi2_setup fun_multi2_setup
#define multi2_ecb_encrypt fun_multi2_ecb_encrypt
#define multi2_ecb_decrypt fun_multi2_ecb_decrypt
#define multi2_test fun_multi2_test
#define multi2_done fun_multi2_done
#define multi2_keysize fun_multi2_keysize
#define ecb_start fun_ecb_start
#define ecb_encrypt fun_ecb_encrypt
#define ecb_decrypt fun_ecb_decrypt
#define ecb_done fun_ecb_done
#define cfb_start fun_cfb_start
#define cfb_encrypt fun_cfb_encrypt
#define cfb_decrypt fun_cfb_decrypt
#define cfb_getiv fun_cfb_getiv
#define cfb_setiv fun_cfb_setiv
#define cfb_done fun_cfb_done
#define ofb_start fun_ofb_start
#define ofb_encrypt fun_ofb_encrypt
#define ofb_decrypt fun_ofb_decrypt
#define ofb_getiv fun_ofb_getiv
#define ofb_setiv fun_ofb_setiv
#define ofb_done fun_ofb_done
#define cbc_start fun_cbc_start
#define cbc_encrypt fun_cbc_encrypt
#define cbc_decrypt fun_cbc_decrypt
#define cbc_getiv fun_cbc_getiv
#define cbc_setiv fun_cbc_setiv
#define cbc_done fun_cbc_done
#define ctr_start fun_ctr_start
#define ctr_encrypt fun_ctr_encrypt
#define ctr_decrypt fun_ctr_decrypt
#define ctr_getiv fun_ctr_getiv
#define ctr_setiv fun_ctr_setiv
#define ctr_done fun_ctr_done
#define ctr_test fun_ctr_test
#define lrw_start fun_lrw_start
#define lrw_encrypt fun_lrw_encrypt
#define lrw_decrypt fun_lrw_decrypt
#define lrw_getiv fun_lrw_getiv
#define lrw_setiv fun_lrw_setiv
#define lrw_done fun_lrw_done
#define lrw_test fun_lrw_test
#define lrw_process fun_lrw_process
#define f8_start fun_f8_start
#define f8_encrypt fun_f8_encrypt
#define f8_decrypt fun_f8_decrypt
#define f8_getiv fun_f8_getiv
#define f8_setiv fun_f8_setiv
#define f8_done fun_f8_done
#define f8_test_mode fun_f8_test_mode
#define xts_start fun_xts_start
#define xts_encrypt fun_xts_encrypt
#define xts_decrypt fun_xts_decrypt
#define xts_done fun_xts_done
#define xts_test fun_xts_test
#define xts_mult_x fun_xts_mult_x
#define find_cipher fun_find_cipher
#define find_cipher_any fun_find_cipher_any
#define find_cipher_id fun_find_cipher_id
#define register_cipher fun_register_cipher
#define unregister_cipher fun_unregister_cipher
#define cipher_is_valid fun_cipher_is_valid

#define setup_mixpn_setup_mix
#define setup_mix2pn_setup_mix2

// cipher-struct 
#define blowfish_key fun_blowfish_key
#define rc5_key fun_rc5_key
#define rc6_key fun_rc6_key
#define saferp_key fun_saferp_key
#define rijndael_key fun_rijndael_key
#define kseed_key fun_kseed_key
#define kasumi_key fun_kasumi_key
#define xtea_key fun_xtea_key
#define twofish_key fun_twofish_key
#define twofish_key fun_twofish_key
#define safer_block_t fun_safer_block_t
#define safer_key_t fun_safer_key_t
#define rc2_key  fun_rc2_key 
#define des_key  fun_des_key 
#define des3_key  fun_des3_key 
#define cast5_key fun_cast5_key
#define noekeon_key  fun_noekeon_key 
#define skipjack_key  fun_skipjack_key 
#define khazad_key  fun_khazad_key 
#define anubis_key  fun_anubis_key 
#define multi2_key  fun_multi2_key 
#define Symmetric_key  fun_Symmetric_key 
#define symmetric_key fun_symmetric_key
#define symmetric_ECB fun_symmetric_ECB
#define symmetric_CFB fun_symmetric_CFB
#define symmetric_OFB fun_symmetric_OFB
#define symmetric_CBC fun_symmetric_CBC
#define symmetric_CTR fun_symmetric_CTR
#define symmetric_LRW fun_symmetric_LRW
#define symmetric_F8 fun_symmetric_F8
#define ltc_cipher_descriptor  fun_ltc_cipher_descriptor 

#define blowfish_desc fun_blowfish_desc
#define rc5_desc fun_rc5_desc
#define rc6_desc fun_rc6_desc
#define rc2_desc fun_rc2_desc
#define saferp_desc fun_saferp_desc
#define safer_k64_desc fun_safer_k64_desc
#define safer_k128_desc fun_safer_k128_desc
#define safer_sk64_desc fun_safer_sk64_desc
#define safer_sk128_desc fun_safer_sk128_desc

#define rijndael_desc  fun_rijndael_desc 
#define cipher_descriptor fun_cipher_descriptor
#define aes_desc fun_aes_desc 
#define symmetric_xts fun_symmetric_xts
#define rijndael_enc_desc fun_rijndael_enc_desc 
#define aes_enc_desc fun_aes_enc_desc 

#define xtea_desc fun_xtea_desc
#define twofish_desc fun_twofish_desc
#define des_desc fun_des_desc
#define des3_desc fun_des3_desc
#define cast5_desc fun_cast5_desc
#define noekeon_desc fun_noekeon_desc
#define skipjack_desc fun_skipjack_desc
#define khazad_desc fun_khazad_desc
#define anubis_desc fun_anubis_desc
#define kseed_desc fun_kseed_desc
#define kasumi_desc fun_kasumi_desc
#define multi2_desc fun_multi2_desc

#define ltc_cipher_mutex fun_ltc_cipher_mutex


// hash
#define chc_register fun_chc_register
#define chc_init fun_chc_init
#define chc_process fun_chc_process
#define chc_done fun_chc_done
#define chc_test fun_chc_test
#define whirlpool_init fun_whirlpool_init
#define whirlpool_process fun_whirlpool_process
#define whirlpool_done fun_whirlpool_done
#define whirlpool_test fun_whirlpool_test
#define sha512_init fun_sha512_init
#define sha512_process fun_sha512_process
#define sha512_done fun_sha512_done
#define sha512_test fun_sha512_test
#define sha384_init fun_sha384_init
#define sha384_done fun_sha384_done
#define sha384_test fun_sha384_test
#define sha256_init fun_sha256_init
#define sha256_process fun_sha256_process
#define sha256_done fun_sha256_done
#define sha256_test fun_sha256_test
#define sha224_init fun_sha224_init
#define sha224_done fun_sha224_done
#define sha224_test fun_sha224_test
#define sha1_init fun_sha1_init
#define sha1_process fun_sha1_process
#define sha1_done fun_sha1_done
#define sha1_test fun_sha1_test
#define md5_init fun_md5_init
#define md5_process fun_md5_process
#define md5_done fun_md5_done
#define md5_test fun_md5_test
#define md4_init fun_md4_init
#define md4_process fun_md4_process
#define md4_done fun_md4_done
#define md4_test fun_md4_test
#define md2_init fun_md2_init
#define md2_process fun_md2_process
#define md2_done fun_md2_done
#define md2_test fun_md2_test
#define tiger_init fun_tiger_init
#define tiger_process fun_tiger_process
#define tiger_done fun_tiger_done
#define tiger_test fun_tiger_test
#define rmd128_init fun_rmd128_init
#define rmd128_process fun_rmd128_process
#define rmd128_done fun_rmd128_done
#define rmd128_test fun_rmd128_test
#define rmd160_init fun_rmd160_init
#define rmd160_process fun_rmd160_process
#define rmd160_done fun_rmd160_done
#define rmd160_test fun_rmd160_test
#define rmd256_init fun_rmd256_init
#define rmd256_process fun_rmd256_process
#define rmd256_done fun_rmd256_done
#define rmd256_test fun_rmd256_test
#define rmd320_init fun_rmd320_init
#define rmd320_process fun_rmd320_process
#define rmd320_done fun_rmd320_done
#define rmd320_test fun_rmd320_test
#define find_hash fun_find_hash
#define find_hash_id fun_find_hash_id
#define find_hash_oid fun_find_hash_oid
#define find_hash_any fun_find_hash_any
#define register_hash fun_register_hash
#define unregister_hash fun_unregister_hash
#define hash_is_valid fun_hash_is_valid
#define hash_memory fun_hash_memory
#define hash_memory_multi fun_hash_memory_multi
#define hash_filehandle fun_hash_filehandle
#define hash_file fun_hash_file

// hash-struct
#define sha512_state  fun_sha512_state 
#define sha256_state  fun_sha256_state 
#define sha1_state  fun_sha1_state 
#define md5_state  fun_md5_state 
#define md4_state  fun_md4_state 
#define tiger_state  fun_tiger_state 
#define md2_state  fun_md2_state 
#define rmd128_state  fun_rmd128_state 
#define rmd160_state  fun_rmd160_state 
#define rmd256_state  fun_rmd256_state 
#define rmd320_state  fun_rmd320_state 
#define whirlpool_state  fun_whirlpool_state 
#define chc_state  fun_chc_state 
#define Hash_state  fun_Hash_state 
#define hash_state fun_hash_state
#define ltc_hash_descriptor  fun_ltc_hash_descriptor 
#define hash_descriptor fun_hash_descriptor
#define ltc_hash_descriptor  fun_ltc_hash_descriptor 
#define chc_desc fun_chc_desc
#define whirlpool_desc fun_whirlpool_desc
#define sha512_desc fun_sha512_desc
#define sha384_desc fun_sha384_desc
#define sha256_desc fun_sha256_desc
#define sha224_desc fun_sha224_desc
#define sha1_desc fun_sha1_desc
#define md5_desc fun_md5_desc
#define md4_desc fun_md4_desc
#define md2_desc fun_md2_desc
#define tiger_desc fun_tiger_desc
#define rmd128_desc fun_rmd128_desc
#define rmd160_desc fun_rmd160_desc
#define rmd256_desc fun_rmd256_desc
#define rmd320_desc fun_rmd320_desc

#define ltc_hash_mutex fun_ltc_hash_mutex


// mac
#define hmac_init fun_hmac_init
#define hmac_process fun_hmac_process
#define hmac_done fun_hmac_done
#define hmac_test fun_hmac_test
#define hmac_memory fun_hmac_memory
#define hmac_memory_multi fun_hmac_memory_multi
#define hmac_file fun_hmac_file
#define omac_init fun_omac_init
#define omac_process fun_omac_process
#define omac_done fun_omac_done
#define omac_memory fun_omac_memory
#define omac_memory_multi fun_omac_memory_multi
#define omac_file fun_omac_file
#define omac_test fun_omac_test
#define pmac_init fun_pmac_init
#define pmac_process fun_pmac_process
#define pmac_done fun_pmac_done
#define pmac_memory fun_pmac_memory
#define pmac_memory_multi fun_pmac_memory_multi
#define pmac_file fun_pmac_file
#define pmac_test fun_pmac_test
#define pmac_ntz fun_pmac_ntz
#define pmac_shift_xor fun_pmac_shift_xor
#define eax_init fun_eax_init
#define eax_encrypt fun_eax_encrypt
#define eax_decrypt fun_eax_decrypt
#define eax_addheader fun_eax_addheader
#define eax_done fun_eax_done
#define eax_encrypt_authenticate_memory fun_eax_encrypt_authenticate_memory
#define eax_decrypt_verify_memory fun_eax_decrypt_verify_memory
#define eax_test fun_eax_test
#define ocb_init fun_ocb_init
#define ocb_encrypt fun_ocb_encrypt
#define ocb_decrypt fun_ocb_decrypt
#define ocb_done_encrypt fun_ocb_done_encrypt
#define ocb_done_decrypt fun_ocb_done_decrypt
#define ocb_encrypt_authenticate_memory fun_ocb_encrypt_authenticate_memory
#define ocb_decrypt_verify_memory fun_ocb_decrypt_verify_memory
#define ocb_test fun_ocb_test
#define ocb_shift_xor fun_ocb_shift_xor
#define ocb_ntz fun_ocb_ntz
#define s_ocb_done fun_s_ocb_done
#define ccm_memory fun_ccm_memory
#define ccm_test fun_ccm_test
#define gcm_gf_mult fun_gcm_gf_mult
#define gcm_mult_h fun_gcm_mult_h
#define gcm_init fun_gcm_init
#define gcm_reset fun_gcm_reset
#define gcm_add_iv fun_gcm_add_iv
#define gcm_add_aad fun_gcm_add_aad
#define gcm_process fun_gcm_process
#define gcm_done fun_gcm_done
#define burn_stack fun_burn_stack
#define error_to_string fun_error_to_string
#define gcm_memory fun_gcm_memory
#define gcm_test fun_gcm_test
#define pelican_init fun_pelican_init
#define pelican_process fun_pelican_process
#define pelican_done fun_pelican_done
#define pelican_test fun_pelican_test
#define pelican_memory fun_pelican_memory
#define xcbc_init fun_xcbc_init
#define xcbc_process fun_xcbc_process
#define xcbc_done fun_xcbc_done
#define xcbc_memory fun_xcbc_memory
#define xcbc_memory_multi fun_xcbc_memory_multi
#define xcbc_file fun_xcbc_file
#define xcbc_test fun_xcbc_test
#define f9_init fun_f9_init
#define f9_process fun_f9_process
#define f9_done fun_f9_done
#define f9_memory fun_f9_memory
#define f9_memory_multi fun_f9_memory_multi
#define f9_file fun_f9_file
#define f9_test fun_f9_test
// mac-struct

#define Hmac_state  fun_Hmac_state 
#define hmac_state fun_hmac_state
#define omac_state fun_omac_state
#define pmac_state fun_pmac_state
#define eax_state fun_eax_state
#define ocb_state fun_ocb_state
#define gcm_state fun_gcm_state
#define pelican_state fun_pelican_state
#define xcbc_state fun_xcbc_state
#define f9_state fun_f9_state
#define gcm_shift_table fun_gcm_shift_table

// math
#define ltc_math_descriptor  fun_ltc_math_descriptor 
#define ltc_mp fun_ltc_mp
#define ltm_desc fun_ltm_desc
#define tfm_desc fun_tfm_desc
#define gmp_desc fun_gmp_desc


// misc
#define base64_encode fun_base64_encode
#define base64_decode fun_base64_decode
#define zeromem fun_zeromem
#define crypt_fsa fun_crypt_fsa
#define crypt_build_settings fun_crypt_build_settings

// PK
#define rand_prime fun_rand_prime
#define rsa_make_key fun_rsa_make_key
#define rsa_exptmod fun_rsa_exptmod
#define rsa_free fun_rsa_free
#define rsa_encrypt_key_ex fun_rsa_encrypt_key_ex
#define rsa_decrypt_key_ex fun_rsa_decrypt_key_ex
#define rsa_sign_hash_ex fun_rsa_sign_hash_ex
#define rsa_verify_hash_ex fun_rsa_verify_hash_ex
#define rsa_export fun_rsa_export
#define rsa_import fun_rsa_import
#define katja_make_key fun_katja_make_key
#define katja_exptmod fun_katja_exptmod
#define katja_free fun_katja_free
#define katja_encrypt_key fun_katja_encrypt_key
#define katja_decrypt_key fun_katja_decrypt_key
#define katja_export fun_katja_export
#define katja_import fun_katja_import
#define ecc_test fun_ecc_test
#define ecc_sizes fun_ecc_sizes
#define ecc_get_size fun_ecc_get_size
#define ecc_make_key fun_ecc_make_key
#define ecc_make_key_ex fun_ecc_make_key_ex
#define ecc_free fun_ecc_free
#define ecc_export fun_ecc_export
#define ecc_import fun_ecc_import
#define ecc_import_ex fun_ecc_import_ex
#define ecc_ansi_x963_export fun_ecc_ansi_x963_export
#define ecc_ansi_x963_import fun_ecc_ansi_x963_import
#define ecc_ansi_x963_import_ex fun_ecc_ansi_x963_import_ex
#define ecc_shared_secret fun_ecc_shared_secret
#define ecc_encrypt_key fun_ecc_encrypt_key
#define ecc_decrypt_key fun_ecc_decrypt_key
#define ecc_sign_hash fun_ecc_sign_hash
#define ecc_verify_hash fun_ecc_verify_hash
#define ltc_ecc_new_point fun_ltc_ecc_new_point
#define ltc_ecc_del_point fun_ltc_ecc_del_point
#define ltc_ecc_is_valid_idx fun_ltc_ecc_is_valid_idx
#define ltc_ecc_projective_dbl_point fun_ltc_ecc_projective_dbl_point
#define ltc_ecc_projective_add_point fun_ltc_ecc_projective_add_point
#define ltc_ecc_fp_mulmod fun_ltc_ecc_fp_mulmod
#define ltc_ecc_fp_save_state fun_ltc_ecc_fp_save_state
#define ltc_ecc_fp_restore_state fun_ltc_ecc_fp_restore_state
#define ltc_ecc_fp_free fun_ltc_ecc_fp_free
#define ltc_ecc_fp_add_point fun_ltc_ecc_fp_add_point
#define ltc_ecc_fp_tablelock fun_ltc_ecc_fp_tablelock
#define ltc_ecc_mulmod fun_ltc_ecc_mulmod
#define ltc_ecc_mul2add fun_ltc_ecc_mul2add
#define ltc_ecc_fp_mul2add fun_ltc_ecc_fp_mul2add
#define ltc_ecc_map fun_ltc_ecc_map
#define dsa_make_key fun_dsa_make_key
#define dsa_free fun_dsa_free
#define dsa_sign_hash_raw fun_dsa_sign_hash_raw
#define dsa_sign_hash fun_dsa_sign_hash
#define dsa_verify_hash_raw fun_dsa_verify_hash_raw
#define dsa_verify_hash fun_dsa_verify_hash
#define dsa_encrypt_key fun_dsa_encrypt_key
#define dsa_decrypt_key fun_dsa_decrypt_key
#define dsa_import fun_dsa_import
#define dsa_export fun_dsa_export
#define dsa_verify_key fun_dsa_verify_key
#define dsa_shared_secret fun_dsa_shared_secret
#define der_encode_sequence_ex fun_der_encode_sequence_ex
#define der_decode_sequence_ex fun_der_decode_sequence_ex
#define der_length_sequence fun_der_length_sequence
#define der_encode_set fun_der_encode_set
#define der_encode_setof fun_der_encode_setof
#define der_encode_sequence_multi fun_der_encode_sequence_multi
#define der_decode_sequence_multi fun_der_decode_sequence_multi
#define der_decode_sequence_flexi fun_der_decode_sequence_flexi
#define der_free_sequence_flexi fun_der_free_sequence_flexi
#define der_sequence_free fun_der_sequence_free
#define der_length_boolean fun_der_length_boolean
#define der_encode_boolean fun_der_encode_boolean
#define der_decode_boolean fun_der_decode_boolean
#define der_encode_integer fun_der_encode_integer
#define der_decode_integer fun_der_decode_integer
#define der_length_integer fun_der_length_integer
#define der_decode_short_integer fun_der_decode_short_integer
#define der_encode_short_integer fun_der_encode_short_integer
#define der_length_short_integer fun_der_length_short_integer
#define der_encode_bit_string fun_der_encode_bit_string
#define der_decode_bit_string fun_der_decode_bit_string
#define der_length_bit_string fun_der_length_bit_string
#define der_encode_octet_string fun_der_encode_octet_string
#define der_decode_octet_string fun_der_decode_octet_string
#define der_length_octet_string fun_der_length_octet_string
#define der_encode_object_identifier fun_der_encode_object_identifier
#define der_decode_object_identifier fun_der_decode_object_identifier
#define der_length_object_identifier fun_der_length_object_identifier
#define der_object_identifier_bits fun_der_object_identifier_bits
#define der_encode_ia5_string fun_der_encode_ia5_string
#define der_decode_ia5_string fun_der_decode_ia5_string
#define der_length_ia5_string fun_der_length_ia5_string
#define der_ia5_char_encode fun_der_ia5_char_encode
#define der_ia5_value_decode fun_der_ia5_value_decode
#define der_encode_printable_string fun_der_encode_printable_string
#define der_decode_printable_string fun_der_decode_printable_string
#define der_length_printable_string fun_der_length_printable_string
#define der_printable_char_encode fun_der_printable_char_encode
#define der_printable_value_decode fun_der_printable_value_decode
#define der_encode_utf8_string fun_der_encode_utf8_string
#define der_decode_utf8_string fun_der_decode_utf8_string
#define der_utf8_charsize fun_der_utf8_charsize
#define der_length_utf8_string fun_der_length_utf8_string
#define der_decode_choice fun_der_decode_choice
#define der_encode_utctime fun_der_encode_utctime
#define der_decode_utctime fun_der_decode_utctime
#define der_length_utctime fun_der_length_utctime
//pk-struct
#define rsa_key fun_rsa_key
#define katja_key fun_katja_key
#define KAT_key  fun_KAT_key 
#define ltc_ecc_set_type fun_ltc_ecc_set_type
#define ecc_point fun_ecc_point
#define ecc_key fun_ecc_key
#define ltc_ecc_set_type  fun_ltc_ecc_set_type 
#define ltc_ecc_sets fun_ltc_ecc_sets
#define dsa_key fun_dsa_key
#define ltc_asn1_list_  fun_ltc_asn1_list_ 
#define ltc_utctime fun_ltc_utctime

//pkcs
#define pkcs_1_mgf1 fun_pkcs_1_mgf1
#define pkcs_1_i2osp fun_pkcs_1_i2osp
#define pkcs_1_os2ip fun_pkcs_1_os2ip
#define pkcs_1_v1_5_encode fun_pkcs_1_v1_5_encode
#define pkcs_1_v1_5_decode fun_pkcs_1_v1_5_decode
#define pkcs_1_oaep_encode fun_pkcs_1_oaep_encode
#define pkcs_1_oaep_decode fun_pkcs_1_oaep_decode
#define pkcs_1_pss_encode fun_pkcs_1_pss_encode
#define pkcs_1_pss_decode fun_pkcs_1_pss_decode
#define pkcs_5_alg1 fun_pkcs_5_alg1
#define pkcs_5_alg2 fun_pkcs_5_alg2

// pkcs-struct
#define ltc_pkcs_1_v1_5_blocks fun_ltc_pkcs_1_v1_5_blocks
#define ltc_pkcs_1_paddings fun_ltc_pkcs_1_paddings


//prng
#define yarrow_start fun_yarrow_start
#define yarrow_add_entropy fun_yarrow_add_entropy
#define yarrow_ready fun_yarrow_ready
#define yarrow_read fun_yarrow_read
#define yarrow_done fun_yarrow_done
#define yarrow_export fun_yarrow_export
#define yarrow_import fun_yarrow_import
#define yarrow_test fun_yarrow_test
#define fortuna_start fun_fortuna_start
#define fortuna_add_entropy fun_fortuna_add_entropy
#define fortuna_ready fun_fortuna_ready
#define fortuna_read fun_fortuna_read
#define fortuna_done fun_fortuna_done
#define fortuna_export fun_fortuna_export
#define fortuna_import fun_fortuna_import
#define fortuna_test fun_fortuna_test
#define rc4_start fun_rc4_start
#define rc4_add_entropy fun_rc4_add_entropy
#define rc4_ready fun_rc4_ready
#define rc4_read fun_rc4_read
#define rc4_done fun_rc4_done
#define rc4_export fun_rc4_export
#define rc4_import fun_rc4_import
#define rc4_test fun_rc4_test
#define sprng_start fun_sprng_start
#define sprng_add_entropy fun_sprng_add_entropy
#define sprng_ready fun_sprng_ready
#define sprng_read fun_sprng_read
#define sprng_done fun_sprng_done
#define sprng_export fun_sprng_export
#define sprng_import fun_sprng_import
#define sprng_test fun_sprng_test
#define sober128_start fun_sober128_start
#define sober128_add_entropy fun_sober128_add_entropy
#define sober128_ready fun_sober128_ready
#define sober128_read fun_sober128_read
#define sober128_done fun_sober128_done
#define sober128_export fun_sober128_export
#define sober128_import fun_sober128_import
#define sober128_test fun_sober128_test
#define find_prng fun_find_prng
#define register_prng fun_register_prng
#define unregister_prng fun_unregister_prng
#define prng_is_valid fun_prng_is_valid
#define rng_get_bytes fun_rng_get_bytes
#define rng_make_prng fun_rng_make_prng

// prng-struct
#define yarrow_prng  fun_yarrow_prng 
#define rc4_prng  fun_rc4_prng 
#define fortuna_prng  fun_fortuna_prng 
#define sober128_prng  fun_sober128_prng 
#define Prng_state  fun_Prng_state 
#define prng_state fun_prng_state
#define ltc_prng_descriptor  fun_ltc_prng_descriptor 
#define prng_descriptor fun_prng_descriptor
#define yarrow_desc fun_yarrow_desc
#define fortuna_desc fun_fortuna_desc
#define rc4_desc fun_rc4_desc
#define sprng_desc fun_sprng_desc
#define sober128_desc fun_sober128_desc
#define ltc_prng_mutex fun_ltc_prng_mutex

// c file
#define ltc_ecc_fp_lock fun_ltc_ecc_fp_lock
#define safer_ebox fun_safer_ebox
#define safer_lbox fun_safer_lbox
