#pragma once

//NOTE FUN_BODY_MACRO_COMBINE 매크로는 헤더툴에서 설정하는것 같은데...??

namespace fun {
struct WeakObjectPtr;
} // namespace fun

#define FUN_DECLARE_DELEGATE(DelegateName)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void)
#define FUN_DECLARE_MULTICAST_DELEGATE(DelegateName)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void)
#define FUN_DECLARE_EVENT(OwningType, EventName)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void)
//#define FUN_DECLARE_DYNAMIC_DELEGATE(DelegateName)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, , FUN_FUNC_CONCAT(*this), void)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(DelegateName)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, , FUN_FUNC_CONCAT(*this), void)
#define FUN_DECLARE_DELEGATE_RET(RetType, DelegateName)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET(RetType, DelegateName)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, , FUN_FUNC_CONCAT(*this), RetType)

#define FUN_DECLARE_DELEGATE_PARAM1(DelegateName, ParamType1)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM1(DelegateName, ParamType1)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1)
#define FUN_DECLARE_EVENT_PARAM1(OwningType, EventName, ParamType1)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM1(DelegateName, ParamType1, ParamName1)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1), FUN_FUNC_CONCAT(*this, InParam1), void, ParamType1)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM1(DelegateName, ParamType1, ParamName1)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1), FUN_FUNC_CONCAT(*this, InParam1), void, ParamType1)
#define FUN_DECLARE_DELEGATE_RET_PARAM1(RetType, DelegateName, ParamType1)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM1(RetType, DelegateName, ParamType1, ParamName1)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1), FUN_FUNC_CONCAT(*this, InParam1), RetType, ParamType1)

#define FUN_DECLARE_DELEGATE_PARAM2(DelegateName, ParamType1, ParamType2)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM2(DelegateName, ParamType1, ParamType2)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2)
#define FUN_DECLARE_EVENT_PARAM2(OwningType, EventName, ParamType1, ParamType2)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM2(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2), FUN_FUNC_CONCAT(*this, InParam1, InParam2), void, ParamType1, ParamType2)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM2(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2), FUN_FUNC_CONCAT(*this, InParam1, InParam2), void, ParamType1, ParamType2)
#define FUN_DECLARE_DELEGATE_RET_PARAM2(RetType, DelegateName, ParamType1, ParamType2)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM2(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2), FUN_FUNC_CONCAT(*this, InParam1, InParam2), RetType, ParamType1, ParamType2)

#define FUN_DECLARE_DELEGATE_PARAM3(DelegateName, ParamType1, ParamType2, ParamType3)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM3(DelegateName, ParamType1, ParamType2, ParamType3)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3)
#define FUN_DECLARE_EVENT_PARAM3(OwningType, EventName, ParamType1, ParamType2, ParamType3)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM3(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3), void, ParamType1, ParamType2, ParamType3)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM3(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3), void, ParamType1, ParamType2, ParamType3)
#define FUN_DECLARE_DELEGATE_RET_PARAM3(RetType, DelegateName, ParamType1, ParamType2, ParamType3)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM3(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3), RetType, ParamType1, ParamType2, ParamType3)

#define FUN_DECLARE_DELEGATE_PARAM4(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM4(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4)
#define FUN_DECLARE_EVENT_PARAM4(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM4(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4), void, ParamType1, ParamType2, ParamType3, ParamType4)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM4(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4), void, ParamType1, ParamType2, ParamType3, ParamType4)
#define FUN_DECLARE_DELEGATE_RET_PARAM4(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM4(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4), RetType, ParamType1, ParamType2, ParamType3, ParamType4)

#define FUN_DECLARE_DELEGATE_PARAM5(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM5(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
#define FUN_DECLARE_EVENT_PARAM5(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM5(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM5(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
#define FUN_DECLARE_DELEGATE_RET_PARAM5(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM5(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5), RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5)

#define FUN_DECLARE_DELEGATE_PARAM6(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM6(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
#define FUN_DECLARE_EVENT_PARAM6(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM6(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM6(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
#define FUN_DECLARE_DELEGATE_RET_PARAM6(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM6(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6), RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6)

#define FUN_DECLARE_DELEGATE_PARAM7(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM7(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
#define FUN_DECLARE_EVENT_PARAM7(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM7(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM7(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
#define FUN_DECLARE_DELEGATE_RET_PARAM7(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM7(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7), RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7)

#define FUN_DECLARE_DELEGATE_PARAM8(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM8(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
#define FUN_DECLARE_EVENT_PARAM8(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM8(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM8(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
#define FUN_DECLARE_DELEGATE_RET_PARAM8(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM8(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8), RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8)

#define FUN_DECLARE_DELEGATE_PARAM9(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
#define FUN_DECLARE_MULTICAST_DELEGATE_PARAM9(DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)  FUNC_FUN_DECLARE_MULTICAST_DELEGATE(DelegateName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
#define FUN_DECLARE_EVENT_PARAM9(OwningType, EventName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)  FUNC_FUN_DECLARE_EVENT(OwningType, EventName, void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_PARAM9(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8, ParamType9, ParamName9)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8, ParamType9 InParam9), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8, InParam9), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
//#define FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE_PARAM9(DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8, ParamType9, ParamName9)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUNC_FUN_DECLARE_DYNAMIC_MULTICAST_DELEGATE(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8, ParamType9 InParam9), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8, InParam9), void, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
#define FUN_DECLARE_DELEGATE_RET_PARAM9(RetType, DelegateName, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)  FUN_FUNC_FUN_DECLARE_DELEGATE(DelegateName, RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
//#define FUN_DECLARE_DYNAMIC_DELEGATE_RET_PARAM9(RetType, DelegateName, ParamType1, ParamName1, ParamType2, ParamName2, ParamType3, ParamName3, ParamType4, ParamName4, ParamType5, ParamName5, ParamType6, ParamName6, ParamType7, ParamName7, ParamType8, ParamName8, ParamType9, ParamName9)  FUN_BODY_MACRO_COMBINE(CURRENT_FILE_ID,_,__LINE__,_DELEGATE)  FUN_FUN_FUNC_FUN_DECLARE_DYNAMIC_DELEGATE_RETVAL(fun::WeakObjectPtr, DelegateName, DelegateName##_DelegateWrapper, RetType, FUN_FUNC_CONCAT(ParamType1 InParam1, ParamType2 InParam2, ParamType3 InParam3, ParamType4 InParam4, ParamType5 InParam5, ParamType6 InParam6, ParamType7 InParam7, ParamType8 InParam8, ParamType9 InParam9), FUN_FUNC_CONCAT(*this, InParam1, InParam2, InParam3, InParam4, InParam5, InParam6, InParam7, InParam8, InParam9), RetType, ParamType1, ParamType2, ParamType3, ParamType4, ParamType5, ParamType6, ParamType7, ParamType8, ParamType9)
