/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#pragma once

#include "FUN.h"
#include "agent_defs.h"
#include "agent_types.h"

namespace fun {
namespace AgentS2C
{
  struct Stub : public fun::RpcStub
  {
    fun::int32 GetDeclaredRpcCount() const override { return AgentS2C::NumRpcFunctions; }
    const fun::RpcId* GetDeclaredRpcIds() const override { return AgentS2C::RpcIds::RpcIdList(); }
    const char** GetDeclaredRpcNames() const override { return AgentS2C::RpcNames::RpcNameList(); }

    // NotifyCredential
    virtual bool NotifyCredential(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint, const bool bAuthentication) { return false; }
    #define DECLARE_RPCSTUB_AgentS2C_NotifyCredential bool NotifyCredential(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint, const bool bAuthentication) override;
    #define IMPLEMENT_RPCSTUB_AgentS2C_NotifyCredential(TClass) bool TClass::NotifyCredential(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint, const bool bAuthentication)
    typedef fun::Function<bool(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint, const bool /* bAuthentication */)> NotifyCredentialFunctionType;
    NotifyCredentialFunctionType OnNotifyCredential;

    // RequestServerAppStop
    virtual bool RequestServerAppStop(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint) { return false; }
    #define DECLARE_RPCSTUB_AgentS2C_RequestServerAppStop bool RequestServerAppStop(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint) override;
    #define IMPLEMENT_RPCSTUB_AgentS2C_RequestServerAppStop(TClass) bool TClass::RequestServerAppStop(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint)
    typedef fun::Function<bool(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint)> RequestServerAppStopFunctionType;
    RequestServerAppStopFunctionType OnRequestServerAppStop;

    // RpcStub interface
    bool ProcessReceivedMessage(fun::ReceivedMessage& received_msg, void* host_tag) override;
  };

} // end of namespace AgentS2C

} // end of namespace fun
