/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "agent.h"

namespace fun {

//==============================================================================
// Service AgentC2S
//==============================================================================

namespace AgentC2S
{
} // end of namespace AgentC2S


//==============================================================================
// Service AgentS2C
//==============================================================================

namespace AgentS2C
{
} // end of namespace AgentS2C


} // end of namespace fun
