/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "emergency.h"

namespace fun {

//==============================================================================
// Service EmergencyC2S
//==============================================================================

namespace EmergencyC2S
{
} // end of namespace EmergencyC2S


//==============================================================================
// Service EmergencyS2C
//==============================================================================

namespace EmergencyS2C
{
} // end of namespace EmergencyS2C


} // end of namespace fun
