/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "emergency_EmergencyS2C_proxy.h"
#include "emergency.h" // _Args, _PArgs

namespace fun {
namespace EmergencyS2C
{
  bool Proxy::EmergencyLogData_AckComplete(const fun::HostId* RpcRemoteIds, const fun::int32 RpcRemoteIdCount, const fun::RpcCallOption& rpc_call_opt)
  {
    fun::MessageOut RpcMessage__;

    // Write RPC function id.
    fun::LiteFormat::Write(RpcMessage__, RpcIds::EmergencyLogData_AckComplete);

    // Write RPC header.
    fun::RpcHeader::WriteOk(RpcMessage__);

    // No RPC function arguments.

    if (notify_send_by_proxy_enabled_ && !engine_specific_only_)
    {
      return RpcCall(RpcRemoteIds, RpcRemoteIdCount, rpc_call_opt, RpcMessage__, RpcNames::EmergencyLogData_AckComplete(), RpcIds::EmergencyLogData_AckComplete, TEXT("{}"));
    }
    else
    {
      return RpcCall(RpcRemoteIds, RpcRemoteIdCount, rpc_call_opt, RpcMessage__, RpcNames::EmergencyLogData_AckComplete(), RpcIds::EmergencyLogData_AckComplete, nullptr);
    }
  }
} // end of namespace EmergencyS2C

} // end of namespace fun
