/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "lan.h"

namespace fun {

//==============================================================================
// Service LanC2C
//==============================================================================

namespace LanC2C
{
} // end of namespace LanC2C


//==============================================================================
// Service LanC2S
//==============================================================================

namespace LanC2S
{
} // end of namespace LanC2S


//==============================================================================
// Service LanS2C
//==============================================================================

namespace LanS2C
{
} // end of namespace LanS2C


} // end of namespace fun
