/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#pragma once

#include "FUN.h"
#include "lan_defs.h"
#include "lan_types.h"

namespace fun {
namespace LanC2C
{
  struct Proxy : public fun::RpcProxy
  {
    fun::int32 GetDeclaredRpcCount() const override { return LanC2C::NumRpcFunctions; }
    const fun::RpcId* GetDeclaredRpcIds() const override { return LanC2C::RpcIds::RpcIdList(); }
    const char** GetDeclaredRpcNames() const override { return LanC2C::RpcNames::RpcNameList(); }

    inline bool Foo(fun::HostId rpc_recvfrom) { return Foo(&rpc_recvfrom, 1, fun::RpcCallOption::Reliable); }
    inline bool Foo(fun::HostId rpc_recvfrom, const fun::RpcCallOption& rpc_call_opt) { return Foo(&rpc_recvfrom, 1, rpc_call_opt); }
    template <typename Allocator>
    inline bool Foo(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds) { return Foo(RpcRemoteIds, fun::RpcCallOption::Reliable); }
    template <typename Allocator>
    inline bool Foo(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds, const fun::RpcCallOption& rpc_call_opt) { return Foo(RpcRemoteIds.ConstData(), RpcRemoteIds.Count(), rpc_call_opt); }
    inline bool Foo(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount) { return Foo(RpcRemoteIds, RpcRemoteIdCount, fun::RpcCallOption::Reliable); }
    bool Foo(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount, const fun::RpcCallOption& rpc_call_opt);
  };
} // end of namespace LanC2C

} // end of namespace fun
