/**
 * Auto-generated by IDL Compiler (2.1.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "net.h"

namespace fun {

//==============================================================================
// Service NetC2C
//==============================================================================

namespace NetC2C
{
} // end of namespace NetC2C


//==============================================================================
// Service NetC2S
//==============================================================================

namespace NetC2S
{
} // end of namespace NetC2S


//==============================================================================
// Service NetS2C
//==============================================================================

namespace NetS2C
{
} // end of namespace NetS2C


} // end of namespace fun
