/**
 * Auto-generated by IDL Compiler (1.0.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#pragma once

#include "FUN.h"
#include "Dump_defs.h"
#include "Dump_types.h"

namespace fun {
namespace DumpS2C
{
  struct Stub : public fun::RpcStub
  {
    fun::int32 GetDeclaredRpcCount() const override { return DumpS2C::NumRpcFunctions; }
    const fun::RpcId* GetDeclaredRpcIds() const override { return DumpS2C::RpcIds::RpcIdList(); }
    const char** GetDeclaredRpcNames() const override { return DumpS2C::RpcNames::RpcNameList(); }

    // ChunkAck
    virtual bool ChunkAck(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint) { return false; }
    #define DECLARE_RPCSTUB_DumpS2C_ChunkAck bool ChunkAck(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint) override;
    #define IMPLEMENT_RPCSTUB_DumpS2C_ChunkAck(TClass) bool TClass::ChunkAck(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint)
    typedef fun::Function<bool(const fun::HostId rpc_recvfrom, const fun::RpcHint& RpcHint)> ChunkAckFunctionType;
    ChunkAckFunctionType OnChunkAck;

    // RpcStub interface
    bool ProcessReceivedMessage(fun::ReceivedMessage& received_msg, void* host_tag) override;
  };

} // end of namespace DumpS2C

} // end of namespace fun
