/**
 * Auto-generated by IDL Compiler (1.0.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#pragma once

#include "FUN.h"
#include "dump_defs.h"
#include "dump_types.h"

namespace fun { namespace Dump {
namespace C2S
{
  struct Proxy : public fun::RpcProxy
  {
    fun::int32 GetDeclaredRpcCount() const override { return C2S::NumRpcFunctions; }
    const fun::RpcId* GetDeclaredRpcIds() const override { return C2S::RpcIds::RpcIdList(); }
    const char** GetDeclaredRpcNames() const override { return C2S::RpcNames::RpcNameList(); }

    inline bool Start(fun::HostId rpc_recvfrom) { return Start(&rpc_recvfrom, 1, fun::RpcCallOption::Reliable); }
    inline bool Start(fun::HostId rpc_recvfrom, const fun::RpcCallOption& RpcCallOption) { return Start(&rpc_recvfrom, 1, RpcCallOption); }
    template <typename Allocator>
    inline bool Start(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds) { return Start(RpcRemoteIds, fun::RpcCallOption::Reliable); }
    template <typename Allocator>
    inline bool Start(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds, const fun::RpcCallOption& RpcCallOption) { return Start(RpcRemoteIds.ConstData(), RpcRemoteIds.Count(), RpcCallOption); }
    inline bool Start(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount) { return Start(RpcRemoteIds, RpcRemoteIdCount, fun::RpcCallOption::Reliable); }
    bool Start(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount, const fun::RpcCallOption& RpcCallOption);

    inline bool Chunk(fun::HostId rpc_recvfrom, const fun::ByteArray& Chunk) { return Chunk(&rpc_recvfrom, 1, fun::RpcCallOption::Reliable, Chunk); }
    inline bool Chunk(fun::HostId rpc_recvfrom, const fun::RpcCallOption& RpcCallOption, const fun::ByteArray& Chunk) { return Chunk(&rpc_recvfrom, 1, RpcCallOption, Chunk); }
    template <typename Allocator>
    inline bool Chunk(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds, const fun::ByteArray& Chunk) { return Chunk(RpcRemoteIds, fun::RpcCallOption::Reliable, Chunk); }
    template <typename Allocator>
    inline bool Chunk(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds, const fun::RpcCallOption& RpcCallOption, const fun::ByteArray& Chunk) { return Chunk(RpcRemoteIds.ConstData(), RpcRemoteIds.Count(), RpcCallOption, Chunk); }
    inline bool Chunk(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount, const fun::ByteArray& Chunk) { return Chunk(RpcRemoteIds, RpcRemoteIdCount, fun::RpcCallOption::Reliable, Chunk); }
    bool Chunk(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount, const fun::RpcCallOption& RpcCallOption, const fun::ByteArray& Chunk);

    inline bool End(fun::HostId rpc_recvfrom) { return End(&rpc_recvfrom, 1, fun::RpcCallOption::Reliable); }
    inline bool End(fun::HostId rpc_recvfrom, const fun::RpcCallOption& RpcCallOption) { return End(&rpc_recvfrom, 1, RpcCallOption); }
    template <typename Allocator>
    inline bool End(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds) { return End(RpcRemoteIds, fun::RpcCallOption::Reliable); }
    template <typename Allocator>
    inline bool End(const fun::Array<fun::HostId,Allocator>& RpcRemoteIds, const fun::RpcCallOption& RpcCallOption) { return End(RpcRemoteIds.ConstData(), RpcRemoteIds.Count(), RpcCallOption); }
    inline bool End(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount) { return End(RpcRemoteIds, RpcRemoteIdCount, fun::RpcCallOption::Reliable); }
    bool End(const fun::HostId* RpcRemoteIds, fun::int32 RpcRemoteIdCount, const fun::RpcCallOption& RpcCallOption);
  };
} // end of namespace C2S

}} // end of namespace fun::Dump
