/**
 * Auto-generated by IDL Compiler (1.0.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "emergency.h"

namespace fun { namespace Emergency {

//==============================================================================
// Service C2S
//==============================================================================

namespace C2S
{
} // end of namespace C2S


//==============================================================================
// Service S2C
//==============================================================================

namespace S2C
{
} // end of namespace S2C


}} // end of namespace fun::Emergency
