/**
 * Auto-generated by IDL Compiler (1.0.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#pragma once

#include "FUN.h"

// Other IDL includes.
#include "engine_types_types.h"

#define IDL_BEGIN_GLOBAL_NAMESPACE }}
#define IDL_END_GLOBAL_NAMESPACE namespace fun { namespace Emergency {

namespace fun { namespace Emergency {

}} // end of namespace fun::Emergency

#undef IDL_BEGIN_GLOBAL_NAMESPACE
#undef IDL_END_GLOBAL_NAMESPACE
